export { default as Hero } from './Hero';
export { default as Navbar } from './Navbar';
export { default as Transition } from './Transition';
export { default as AboutUs } from './AboutUs';
export { default as Projects } from './Projects';
export { default as Services } from './Services';
export { default as Testimonials } from './Testimonials';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';
